trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
# Use Java 11 (stable)
- task: UseJavaVersion@1
  inputs:
    versionSpec: '11'
    architecture: 'x64'

# Cache Maven dependencies (optional but fast)
- task: Cache@2
  inputs:
    key: 'maven | "$(Agent.OS)" | **/pom.xml'
    path: ~/.m2/repository

# Maven Build
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'Path'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package -DskipTests'
