trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
# Install Java (safe version for most projects)
- task: UseJavaVersion@1
  inputs:
    versionSpec: '11'
    architecture: 'x64'

# Maven build
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'   # change if your pom.xml is in a folder
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'Path'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package -DskipTests -X'
